name: Build Lidar

run-name: Build Lidar ${{github.sha}}

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lidar
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Fetch submodule
        run: git submodule update --init
      - name: Install X11
        run: sudo apt update && sudo apt install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev
      - name: Build rplidar_sdk
        working-directory: ./lidar/rplidar_sdk
        run: make
      - name: Build lidar
        run: mkdir build && cd build && cmake .. && make
