name: Check Nano

run-name: Check Nano ${{github.sha}}

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./arduino_nano
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Check code
        run: pio check
      - name: Build project
        run: pio run
